import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import NavBar from '../components/NavBar';
import Footer from '../components/Footer';

export default function Apropos() {
  return (
    <div className="">
      <Head>
        <title>
          Frédérique Dupleich Céramiste - À propos
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={`${styles.my_container2} container mx-auto`}>
          <div className="row mx-0 justify-content-center">
            <NavBar />
          </div>
          <div className="row mx-0 pb-5 mt-5 justify-content-center">
            <div className="col-11 col-md-10 col-lg-5 px-O">
              <Image
                className=""
                src="/images/four.jpeg"
                alt=""
                width={2448}
                height={3264}
                layout="responsive"
                priority="true"
              />
            </div>
            <div className={`${styles.aboutme} col-9 col-md-8 col-lg-6 bg-light text-center text-md-start rounded p-5 `}>
              <div className="lh-lg">
                &ldquo;De Frédérique, je sais certaines influences, les chocs esthétiques,
                les strates accumulées de sa mémoire sensible.
                Son Oeil assuré guide ses mains affairées sur la boule de terre,
                souvent de grès, parfois de porcelaine.
              </div>
              <div className="lh-lg">
                Ici, le tour est remisé, le moule inexistant.
                Il n&lsquo;est pas question de gagner du temps.
                Frédérique avance confiante dans les processus plus lents
                du pincé, du colombin ou de la plaque.
              </div>
              <div className="fw-bold fs-5 my-3">La main cherche, creuse, pince, modèle, s&lsquo;agite et s&lsquo;exalte.</div>
              <div className="lh-lg">
                La forme ainsi révélée, il s&lsquo;agit parfois de lui donner du grain,
                de la texture en grattant, scarifiant, &ldquo;empreintant&ldquo; la surface.
              </div>
              <div className="lh-lg">
                Ses propres émaux viennent envelopper chacune des pièces.
                Comme une peau.
                Ses blancs &ldquo;cailloux&ldquo;, ses gris &ldquo;célestes&ldquo; sont autant de
                {' '}
                <span className="fw-bold fs-5">
                  teintes
                  intemporelles
                </span>
                {' '}
                à associer à toutes les autres.
                Ses pièces en terre touchent.&ldquo;
              </div>
              <div className="mt-4 text-end">
                Sandrine
                <img className="ms-2" alt="Emoji" src="https://s.yimg.com/nq/yemoji_assets/latest/yemoji_assets/1f33f.png" width="16" height="16" />
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </div>
  );
}
