import React, { useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import emailjs from "emailjs-com";
import Swal from "sweetalert2";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";

export default function Contact() {
  function sendEmail(e) {
    e.preventDefault();

    emailjs
      .sendForm(
        "service_du0nfnd",
        "contact_form",
        e.target,
        "tGb-Y9swpak_7uigt"
      )
      .then(
        (result) => {
          console.log(result.text);
          Swal.fire({
            icon: "success",
            title: "Super !",
            text: "Votre message a bien été envoyé",
          });
          document.getElementById("contact_form").reset();
          window.grecaptcha.reset();
        },
        (error) => {
          console.log(error.text);
        }
      );
  }

  return (
    <div className="">
      <Head>
        <title>Frédérique Dupleich Céramiste - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`pb-2 d-flex flex-column justify-content-between`}>
        <div className={`${styles.my_container} container-xl mx-auto`}>
          <div className="row mx-0 justify-content-center">
            <NavBar />
          </div>
          <div className="row mx-0 mx-md-5 mb-2 justify-content-center align-items-center ">
            <div className={`col col-lg-10 col-xxl-9`}>
              <div className="card p-0 mb-3 shadow-lg border-0">
                <div
                  className={`${styles.bg_card} row g-0 p-4 d-flex flex-column flex-lg-row align-items-center bg-light rounded`}
                >
                  <div className="col col-md-6 mt-md-4 mt-lg-0">
                    <img
                      src="/images/vue1.jpg"
                      className="img-fluid rounded-start"
                      alt="poterie en grès"
                    />
                  </div>
                  <div className="col text-center">
                    <div className="card-body flex align-items-stretch">
                      <div className=" mb-5 text-center">
                        <div className="fs-5 mb-3 ">
                          <i className="me-3 bi bi-telephone" />
                          07 69 29 63 82
                        </div>
                      </div>
                      <h5 className="mb-4 text-center">
                        Laissez-moi un message
                      </h5>
                      <form
                        className="text-center rounded mx-4 "
                        id="contact_form"
                        onSubmit={sendEmail}
                        //action="?"
                        //method="POST"
                      >
                        <input type="hidden" name="contact_number" />
                        <div className="">
                          <label htmlFor="name" />
                          <input
                            className="form-control"
                            type="text"
                            name="user_name"
                            id="name"
                            placeholder="Votre nom"
                            required
                          />
                          <label htmlFor="email" />
                          <input
                            className="form-control"
                            type="email"
                            name="user_email"
                            id="email"
                            placeholder="Votre adresse mail"
                            required
                          />
                        </div>
                        <div>
                          <label htmlFor="message" />
                          <textarea
                            className="mb-3 form-control"
                            rows="5"
                            name="message"
                            id="message"
                            placeholder="Votre message"
                            required
                          />
                        </div>
                        {/*  <div
                          className="g-recaptcha d-flex justify-content-center"
                          data-sitekey="6LcuH_sfAAAAAAOSk3mPPsiNfjiALOe5NivOzhCw"
                        ></div> */}
                        <button
                          className="btn btn-outline-dark mt-3 mb-3 fw-bold"
                          type="submit"
                          value="Send"
                        >
                          <i className="bi bi-envelope-fill" /> ENVOYER
                        </button>
                      </form>
                      {/* <form action="?" method="POST">
                        <br />
                        <input type="submit" value="Submit" />
                      </form> */}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </div>
  );
}
