import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import { categories } from "../data/dataList";
import "react-image-lightbox/style.css";
import CardGallery from "../components/CardGallery";

export default function Galerie() {
  return (
    <div className="">
      <Head>
        <title>Frédérique Dupleich Céramiste - Galerie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={`${styles.my_container2} container-xl mx-auto`}>
          <div className="row mx-0 justify-content-center">
            <NavBar />
          </div>
          <div className="row mx-0 mx-xl-5 pb-5 text-center justify-content-center">
            <div className="col mx-auto mb-3 d-flex flex-column flex-md-row flex-wrap justify-content-center">
              {categories.map((category) => (
                <div className="" key={category.id}>
                  <CardGallery
                    id={category.id}
                    name={category.name}
                    image={category.image}
                    gallery={category.gallery}
                  />
                </div>
              ))}
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </div>
  );
}
