import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/NavBar'
import Card from 'react-bootstrap/Card'
import Footer from '../components/Footer'

export default function Galerie() {
  return (
    <div className="">
      <Head>
        <title>Frédérique Dupleich Céramiste - Galerie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
            <div className={`${styles.my_container} container-fluid mx-auto`}>            
                <div className="row mx-0 justify-content-center">
                    <NavBar/>
                </div>
                <div className="row mx-5 mb-5 pt-5 pb-5 text-center justify-content-center">
                    <div className="col-8 mx-auto mb-2 d-flex flex-column flex-md-row flex-wrap justify-content-center">
                        <div className="">
                            <img className={`${styles.my_card}`} src="/images/bols.jpeg" alt="bols en gres"/>
                            <div >Bols-Tasses</div>
                        </div>
                        <div className="">
                            <img className={`${styles.my_card}`} src="/images/saladier1.jpeg" alt="..."/>
                            <div >Saladiers</div>
                        </div>
                        <div className="">
                            <img className={`${styles.my_card}`} src="/images/spoons2.jpeg" alt="..."/>
                            <div >Cuillères</div>
                        </div>
                        <div className="">
                            <img className={`${styles.my_card}`} src="/images/mix_vegetal3.jpeg" alt="..."/>
                            <div >Fruits-Végétaux</div>
                        </div>
                    </div>
                </div>      
            </div>

            
            <Footer/>
        </main>
    </div>
  )
}
