import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";
import Card from "react-bootstrap/Card";
import Footer from "../components/Footer";
import Course from "../components/Course";
import { courses } from "../data/dataList";

export default function Atelier() {
  return (
    <div className="">
      <Head>
        <title>Frédérique Dupleich Céramiste - Stages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`pb-2 d-flex flex-column justify-content-between`}>
        <div className={`${styles.my_container} container-xl pb-2 mx-auto`}>
          <div className="row mx-0 justify-content-center">
            <NavBar />
          </div>
          <div className="row mx-0 mx-md-5 mb-2 justify-content-center align-items-center">
            <div className={`col col-lg-11 col-xxl-9`}>
              <div className="card p-0 mb-3 shadow-lg border-0">
                <div
                  className={`${styles.bg_card} row g-0 p-4 d-flex flex-column flex-lg-row align-items-center border-0 rounded`}
                >
                  <div className="col col-md-6 mt-md-4 mt-lg-0">
                    <img
                      src="/images/mains2.jpg"
                      className="img-fluid rounded-start"
                      alt="photo cours poterie"
                    />
                  </div>
                  <div className="col text-center">
                    <div className="card-body">
                      <h2 className=" mb-5 mb-lg-4 fs-1">Stages</h2>
                      {courses.map((item, index) => (
                        <Course cours={item} key={index} />
                      ))}

                      <div className="text-muted text-center mt-2">
                        Le prix des stages comprend la terre, l’émail, le
                        matériel et les cuissons
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row mx-5 mb-3 justify-content-center align-items-center">
            <div className={`col text-center`}>
              <div className="mt-1 mb-lg-5 text-center fw-bold">
                Les stages se déroulent dans mon atelier situé à Tournefeuille
                (31).
              </div>
              <div className="text-center mt-4 mt-xXl-2 mb-4">
                <button className="border shadow rounded-pill px-3 py-2">
                  <a className="" href="/contact">
                    Renseignements / Inscriptions
                  </a>
                </button>
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </div>
  );
}
